name: commonapp
description: A new Flutter project.

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^0.1.0
  flutter_webview_plugin: ^0.3.0
  share: ^0.5.3
  synchronized: ^1.5.3
  shared_preferences: ^0.4.3

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/alucard.jpg
    - assets/girl.jpeg
    - img/

  fonts:
      - family: Nunito
        fonts:
          - asset: assets/Nunito.ttf